version: "3"
services:

  gdal:
    build:
      dockerfile: ./Dockerfile
      context: ./osm
    env_file:
      - ./.env
    depends_on:
      - postgres
    command: bash -c "chmod +x /osm/export.sh && ./osm/export.sh"
    volumes:
      - ./osm:/osm

  postgres:
    image: "postgis/postgis"

    env_file:
      - .env
    ports:
    - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data/


volumes:
  db-data: