// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/rules/create": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create New Rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "Create New Rule",
                "parameters": [
                    {
                        "description": "rule",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/surge.RuleDto"
                        }
                    }
                ],
                "responses": {
                    "201": {},
                    "401": {}
                }
            }
        },
        "/rules/delete": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete One Rule By It's ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "Delete Rule",
                "parameters": [
                    {
                        "description": "Rule ID",
                        "name": "ID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/surge.DeleteRuleDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {},
                    "401": {}
                }
            }
        },
        "/rules/get/all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get All Rules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rule"
                ],
                "summary": "Get All Rules",
                "responses": {
                    "200": {},
                    "401": {}
                }
            }
        },
        "/surge/ride": {
            "post": {
                "description": "Ride request: calculates coefficient and increments that district's requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Surge"
                ],
                "summary": "Coefficient Request",
                "parameters": [
                    {
                        "description": "Latitude and Longitude",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/surge.LatLonDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {}
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Login Admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "login info",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UsersDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {},
                    "401": {}
                }
            }
        },
        "/users/register": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create User By Admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "user info",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UsersDto"
                        }
                    }
                ],
                "responses": {
                    "201": {},
                    "400": {},
                    "401": {}
                }
            }
        },
        "/users/update/password": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Change your password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update Password",
                "parameters": [
                    {
                        "description": "user new password",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdatePasswordDto"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {},
                    "401": {}
                }
            }
        }
    },
    "definitions": {
        "surge.DeleteRuleDto": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "surge.LatLonDto": {
            "type": "object",
            "required": [
                "lat",
                "lon"
            ],
            "properties": {
                "lat": {
                    "type": "number",
                    "example": 51.13199462890625
                },
                "lon": {
                    "type": "number",
                    "example": 35.73425097869431
                }
            }
        },
        "surge.RuleDto": {
            "type": "object",
            "required": [
                "coefficient",
                "threshold"
            ],
            "properties": {
                "coefficient": {
                    "type": "number",
                    "example": 1.12
                },
                "threshold": {
                    "type": "integer",
                    "example": 12
                }
            }
        },
        "user.UpdatePasswordDto": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "description": "password must be longer than 4 chars",
                    "type": "string"
                }
            }
        },
        "user.UsersDto": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "password must be longer than 4 chars",
                    "type": "string",
                    "example": "admin"
                },
                "username": {
                    "description": "username must be longer than 4 chars",
                    "type": "string",
                    "example": "admin"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Surge",
	Description: "Snapp Surge Service.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
